# Generated by Django 3.0.5 on 2020-08-19 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20200814_0420'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Action',
            new_name='Actor',
        ),
    ]
